---
- name: Rôle sudo-user
  hosts: all
  become: true
  roles:
    - sudo-user
  tags:
    - sudo-user
    - base
    - iut-base
    - iut-pedago
    - desktop
    - iut-desktop

- name: Rôle base
  hosts: all
  become: true
  roles:
    - base
  tags:
    - base
    - iut-base
    - iut-pedago
    - desktop
    - iut-desktop

- name: Rôle iut-base
  hosts: all
  become: true
  roles:
    - iut-base
  tags:
    - iut-base
    - iut-pedago
    - iut-desktop

- name: Rôle iut-pedago
  hosts: all
  become: true
  roles:
    - iut-pedago
  tags:
    - iut-pedago
    - iut-desktop

- name: Rôle desktop
  hosts: all
  become: true
  roles:
    - desktop
  tags:
    - desktop
    - iut-desktop

- name: Rôle iut-desktop
  hosts: all
  become: true
  roles:
    - iut-desktop
  tags:
    - iut-desktop
