---
- name: Configuration bootstrap
  hosts: all
  become: true
  roles:
    - base
  tags:
    - base

- name: Rôle iut-desktop
  hosts: all
  become: true
  roles:
    - desktop
  tags:
    - desktop

- name: Création de l'utilisateur sudo
  hosts: all
  become: true
  roles:
    - sudo-user
  tags:
    - sudo-user

- name: Rôle iut-base
  hosts: all
  become: true
  roles:
    - iut-base
  tags:
    - iut-base

- name: Rôle iut-pedago
  hosts: all
  become: true
  roles:
    - iut-pedago
  tags:
    - iut-pedago

- name: Rôle iut-desktop
  hosts: all
  become: true
  roles:
    - iut-desktop
  tags:
    - iut-desktop
