---
- name: Vérifier si Ghostty est déjà installé
  shell: dpkg-query -W -f='${Status}' ghostty 2>/dev/null | grep -q "install ok installed"
  register: ghostty_installed
  failed_when: false
  changed_when: false

- name: Créer un répertoire temporaire pour le téléchargement
  become: true
  file:
    path: /tmp/ghostty_download
    state: directory
    mode: "0755"
  when: ghostty_installed.rc != 0

- name: Télécharger le paquet Ghostty
  become: true
  get_url:
    url: https://github.com/mkasberg/ghostty-ubuntu/releases/download/1.1.3-0-ppa2/ghostty_1.1.3-0.ppa2_amd64_24.10.deb
    dest: /tmp/ghostty_download/ghostty.deb
    mode: "0644"
  when: ghostty_installed.rc != 0
  register: ghostty_downloaded

- name: Installer le paquet Ghostty
  become: true
  apt:
    deb: /tmp/ghostty_download/ghostty.deb
    state: present
  when: ghostty_installed.rc != 0

- name: Nettoyer le répertoire temporaire
  become: true
  file:
    path: /tmp/ghostty_download
    state: absent
  when: ghostty_installed.rc != 0
