---
- name: "Créer les dossiers bin, .local/bin et dev/src/github.com/humboldtux dans le home de {{ sudo_user }}"
  become: true
  become_user: "{{ sudo_user }}"
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "~/bin"
    - "~/.local/bin"
    - "~/dev/src/github.com/humboldtux"
