---
- name: Vérifier si le dossier ~/.config/nvim existe
  become: true
  become_user: "{{ sudo_user }}"
  stat:
    path: ~/.config/nvim
  register: nvim_confdir

- name: Définir l'URL du dépôt Git en fonction de l'utilisateur
  set_fact:
    nvim_repo_url: "{{ 'https://github.com/humboldtux/lazyvim.git' if sudo_user in ['sirm', 'snap', 'admin'] else 'git@github.com:humboldtux/lazyvim.git' }}"

- name: Cloner la config Neovim si absente
  become: true
  become_user: "{{ sudo_user }}"
  git:
    repo: "{{ nvim_repo_url }}"
    dest: ~/.config/nvim
    clone: yes
    update: no
  when: not nvim_confdir.stat.exists
  register: nvim_clone

- name: Ajouter ~/.config/nvim à gita si cloné
  become: true
  become_user: "{{ sudo_user }}"
  shell: gita add ~/.config/nvim
  args:
    executable: /bin/bash
  when: nvim_clone is changed
