---
# Pour générer un mot de passe chiffré compatible avec cette tâche, utilisez l'une des commandes suivantes :
#
# 1. Avec Python (recommandé) :
#    python3 -c 'import crypt; print(crypt.crypt("votre_mot_de_passe", crypt.mksalt(crypt.METHOD_SHA512)))'
#
# 2. Avec mkpasswd (disponible dans le paquet whois) :
#    mkpasswd --method=SHA-512 --rounds=656000 "votre_mot_de_passe"
#
# 3. Avec Ansible (dans un playbook séparé) :
#    ansible localhost -m debug -a "msg={{ 'votre_mot_de_passe' | password_hash('sha512', 'votre_sel_aléatoire') }}"
#
# Le mot de passe chiffré doit commencer par $6$ (indiquant SHA-512)

- name: Définir le mot de passe pour l'utilisateur sudo_user
  become: true
  user:
    name: "{{ sudo_user }}"
    password: "$6$Vuz.NVUGaQ6U9cSv$lLVbdBS19ObR5VyS8vSm8F12M7awnfYuPc2FKgxlJETV8yp6z3WGjbWFNg2.hRhSIQa7grt9EtWCRxldt75bM/"
    update_password: always
  when: "'iut-desktop' in ansible_run_tags and inventory_hostname != 'LINSERV-INFO-01'"
