---
- name: Installer curl
  become: true
  apt:
    name: curl
    state: present
    update_cache: yes

- name: Vérifier si pkgx est déjà installé
  become: true
  stat:
    path: "/usr/local/bin/pkgx"
  register: pkgx_bin

- name: "Installer pkgx si absent"
  become: true
  shell: curl https://pkgx.sh | sh
  args:
    executable: /bin/bash
  when: not pkgx_bin.stat.exists
