---
- name: Installer la configuration 60unattended-upgrades
  become: true
  copy:
    src: apt/files/60unattended-upgrades
    dest: /etc/apt/apt.conf.d/60unattended-upgrades
    mode: '0644'
    owner: root
    group: root
    validate: cat %s
    backup: yes

- name: Installer la configuration 99fix-dpkg-before-unattended
  become: true
  copy:
    src: apt/files/99fix-dpkg-before-unattended
    dest: /etc/apt/apt.conf.d/99fix-dpkg-before-unattended
    mode: '0644'
    owner: root
    group: root
    validate: cat %s
    backup: yes
