---
- name: Déployer la configuration de GRUB
  become: true
  block:
    - name: Créer le répertoire pour les fichiers GRUB
      file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
        owner: root
        group: root
      loop:
        - /etc/grub.d

    - name: Déployer /etc/grub.d/01_users
      copy:
        src: grub/files/01_users
        dest: /etc/grub.d/01_users
        mode: "0750"
        owner: root
        group: root
      register: grub_01_users

    - name: Déployer /etc/grub.d/10_linux
      copy:
        src: grub/files/10_linux
        dest: /etc/grub.d/10_linux
        mode: "0750"
        owner: root
        group: root
      register: grub_10_linux

    - name: Déployer /etc/grub.d/30_os-prober
      copy:
        src: grub/files/30_os-prober
        dest: /etc/grub.d/30_os-prober
        mode: "0750"
        owner: root
        group: root
      register: grub_09_os_prober

    - name: Déployer /etc/default/grub
      copy:
        src: grub/files/default_grub
        dest: /etc/default/grub
        mode: "0644"
        owner: root
        group: root
      register: grub_default

    - name: Exécuter update-grub
      command: update-grub
      when: grub_01_users.changed or grub_10_linux.changed or grub_09_os_prober.changed or grub_default.changed
