---
- name: Récupérer le nom d'hôte
  ansible.builtin.command: hostname
  register: hostname_result
  changed_when: false

- name: Créer le fichier sudoers pour ansible-postes
  become: true
  copy:
    src: sudo/files/ansible-postes
    dest: /etc/sudoers.d/ansible-postes
    mode: '0440'
    owner: root
    group: root
    validate: 'visudo -cf %s'
    backup: yes
  when: hostname_result.stdout != 'LINSERV-INFO-01'
