---
- name: Récupérer le nom d'hôte
  ansible.builtin.command: hostname
  register: hostname_result
  changed_when: false

- name: Installation des paquets Veyon
  become: true
  apt:
    name:
      - libqca-qt5-2-plugins
      - veyon-configurator
      - veyon-master
      - veyon-plugins
      - veyon-service
    state: present
  when: hostname_result.stdout != 'LINSERV-INFO-01'

- name: Créer le répertoire pour la configuration Veyon
  become: true
  file:
    path: /etc/xdg/Veyon Solutions
    state: directory
    mode: '0755'
    owner: root
    group: root
  when: hostname_result.stdout != 'LINSERV-INFO-01'

- name: Installer le fichier de configuration Veyon
  become: true
  copy:
    src: veyon/files/Veyon.conf
    dest: /etc/xdg/Veyon Solutions/Veyon.conf
    mode: '0644'
    owner: root
    group: root
    backup: yes
  when: hostname_result.stdout != 'LINSERV-INFO-01'
  register: veyon_conf

- name: Installer le fichier de démarrage automatique Veyon
  become: true
  copy:
    src: veyon/files/veyon.desktop
    dest: /etc/xdg/autostart/veyon.desktop
    mode: '0644'
    owner: root
    group: root
    backup: yes
  when: hostname_result.stdout != 'LINSERV-INFO-01'

- name: Désactiver et arrêter le service Veyon
  become: true
  service:
    name: veyon
    state: stopped
    enabled: false
  register: veyon_service
  retries: 3
  delay: 5
  until: veyon_service is success
  when: hostname_result.stdout != 'LINSERV-INFO-01'
