---
- name: S'assurer que non-free est présent sur toutes les lignes deb/deb-src
  become: true
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list
    regexp: '^(deb(?:-src)?\\s+\\S+\\s+\\S+\\s+.*)$'
    line: "{{ item }}"
  loop: "{{ lookup('file', '/etc/apt/sources.list').splitlines() | map('regex_replace', '^(deb(?:-src)?\\s+\\S+\\s+\\S+\\s+.*)$', '\\1 non-free') | list }}"
  when: "'non-free' not in item"

- name: S'assurer que non-free-firmware est présent sur toutes les lignes deb/deb-src
  become: true
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list
    regexp: '^(deb(?:-src)?\\s+\\S+\\s+\\S+\\s+.*)$'
    line: "{{ item }}"
  loop: "{{ lookup('file', '/etc/apt/sources.list').splitlines() | map('regex_replace', '^(deb(?:-src)?\\s+\\S+\\s+\\S+\\s+.*)$', '\\1 non-free-firmware') | list }}"
  when: "'non-free-firmware' not in item"
