---
- import_tasks: apt-repos.yml
- import_tasks: wakemeops.yml
- import_tasks: packages.yml
- import_tasks: stew.yml
- import_tasks: pipx-packages.yml
- import_tasks: xpanes.yml

- import_tasks: sentinel-one.yml
  when: sentinel_one is defined
