---
- name: Installer une liste de paquets utiles
  become: true
  apt:
    name:
      - anacron
      - apticron
      - atool
      - backupninja
      - bat
      - bottom
      - broot
      - build-essential
      - clang
      - clang-tools
      - curl
      - clusterssh
      - czkawka-cli
      - detox
      - diffoscope-minimal
      - direnv
      - dkms
      - dos2unix
      - duf
      - dust
      - eza
      - fd-find
      - ffmpeg
      - ffmpegthumbnailer
      - firmware-linux
      - firmware-linux-free
      - firmware-linux-nonfree
      - ftp
      - fuse3
      - fzf
      - gdebi
      - git
      - git-delta
      - gita
      - glow
      - golang
      - gum
      - htop
      - iftop
      - iotop
      - iotop-c
      - jc
      - jq
      - khal
      - kmon
      - lazydocker
      - lazygit
      - ldap-utils
      - libproxychains4
      - libssl-dev
      - linux-headers-amd64
      - lldb
      - lnav
      - locate
      - lsd
      - luarocks
      - mariadb-client
      - miller
      - manpages-posix
      - manpages-posix-dev
      - moreutils
      - nano
      - ncdu
      - needrestart
      - neovim
      - newsboat
      - ntpsec-ntpdate
      - nvme-cli
      - nushell
      - odt2txt
      - pdftk
      - pipx
      - pkg-config
      - poppler-utils
      - proxychains4
      - putty-tools
      - python3-ldap
      - python3-pil
      - python3-pip
      - python3-venv
      - ranger
      - reptyr
      - restic
      - resticprofile
      - resvg
      - smbclient
      - starship
      - vhs
      - xq
      - yadm
      - yt-dlp
      - zellij
      - zoxide
    state: present
    update_cache: yes
